name: Travel Link
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50904
title: Travel Link
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5374625674448907
  lightness: 0.45840304833836854
  saturation: 0.9066257290542126
  rhythmicContrast: 0.416381923481822
purpose: []
