name: Travel Link
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50904
title: Travel Link
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ae3084'
    - '#fefefe'
    - '#f5c000'
    - '#ff8268'
  brandStrength: 0.625
  lightness: 0.45840304833836854
  saturation: 0.9066257290542126
  rhythmicContrast: 0.25
purpose: []
